[tool.poetry]
name = "myhomesmartai"
version = "0.1.0"
description = ""
authors = ["Mihail Brazdis"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
streamlit = "^1.39.0"
langchain = "^0.3.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
